import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import Navbar from "./Navbar/page";
import { NextUIProvider } from "@nextui-org/react";
import { Suspense } from 'react'
import Loading from "./loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black">
        <NextUIProvider>
          <Navbar />
          <Suspense fallback={<Loading/>}>
          {children}
      </Suspense>
       
        </NextUIProvider>
      </body>
    </html>
  );
}
